target:
  service: amlk8s
  name: itpmtlv100cl1
  vc: MSRMTLVC1
  # itpeastusv100cl
  # service: aml
  # name: canada24

environment:
  # image: nvidia/pytorch:20.12-py3
  # registry: nvcr.io
  image: richardbaihe/pytorch:azure
  setup:
    - export MKL_SERVICE_FORCE_INTEL=1 
    - python -m nltk.downloader punkt wordnet
    
code:
  local_dir: $CONFIG_DIR/src
  
data:
  local_dir: $CONFIG_DIR/data/wikitext-103
  remote_dir: data/wikitext-103

# list of jobs to run, we run 2 jobs in this example
# For large model, the minimum GPU configuration is a 8*32GB single node.
jobs:
- name: train_large_segaxl_hp
  sku: G8
  command:
  - python train.py 
    --job_name train_large_segaxl_hp
    --pacing_function step
    --pacing_unit step
    --a 0.12
    --b 0.8
    --wn_layer 5
    --mix_vocab
    --input_root
    --max_step 400000
    --batch_size 128
    --gpu0_bsz 8
    --mem_len 384
    --sega
    --model_size large
    --dataset wt103
    --adaptive
    --fp16
    --dynamic-loss-scale
    --multi_gpu
    --cuda
    --pt
    --do_train
    --do_test
    --load_checkpoint latest 
    --work_dir ${A_PATH}

search:
  job_template:
    name: search_{experiment_name:s}_{auto:s}
    sku: G4
    command:
    - python -m torch.distributed.launch
      --nproc_per_node 4 
      --nnodes 1 
      --node_rank 0 
      --master_addr 127.0.0.1 
      --master_port 16010
      train.py 
      --job_name search_base_bsz_16_pf_{pacing_function}_pu_{pacing_unit}_{a}_{b}
      --pacing_function {pacing_function}
      --pacing_unit {pacing_unit}
      --a {a}
      --b {b}
      --model_size base
      --max_step 200000
      --batch_size 16
      --dataset wt103
      --mix_vocab
      --input_root
      --mem_len 0
      --adaptive
      --fp16
      --dynamic-loss-scale
      --multi_gpu
      --cuda
      --pt
      --do_train
      --do_test
      --div_val 4
  type: grid
  max_trials: 12
  params:
    - name: pacing_function
      spec: discrete
      values: ['step','linear']
    - name: pacing_unit
      spec: discrete
      values: ['step','epoch']
    - name: a
      spec: discrete
      values: [0.06, 0.12, 0.18, 0.24]
    - name: b
      spec: discrete
      values: [1, 0.8, 0.6]

